# Generated by Django 5.0.6 on 2025-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
    ]
